# Generated by Django 3.1.5 on 2021-02-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='allay',
            field=models.TextField(max_length=150, verbose_name='Allay'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.TextField(max_length=150, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.TextField(max_length=150, verbose_name='Street'),
        ),
    ]
