# Generated by Django 3.1.5 on 2021-02-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_categorybrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='unit',
            field=models.CharField(choices=[('TO', 'Toman'), ('RI', 'Rial')], default='TO', max_length=5),
        ),
    ]
