# Generated by Django 3.1.5 on 2021-02-13 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('product', '0003_shopproduct_unit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shopproduct',
            unique_together={('product', 'shop')},
        ),
    ]
