# Generated by Django 3.1.5 on 2021-02-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210213_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='unit',
            field=models.CharField(choices=[('تومان', 'Toman'), ('ریال', 'Rial')], default='تومان', max_length=5),
        ),
    ]
