# Generated by Django 3.1.5 on 2021-02-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210213_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/products/images', verbose_name='Image'),
        ),
    ]
