# Generated by Django 3.1.5 on 2021-02-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_commentlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='publish_time',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Publish at'),
        ),
    ]
